### ISSUE TITLE
Add tags to repo so releases show up on github

### ISSUE THREAD

**Issue by richienyhus** [Giova84/LittleWriter#10]
This should work for the three releases made so far:

`git tag -a v1.0 80874b5`
`git tag -a v1.1 23fd858`
`git tag -a v1.2 3de45ba`
`git push origin --tags`

**Comment by Giova84** [comment]
Thank you for the nice suggestion; I wasn't aware of this feature.
Anyway, now is done: https://github.com/Giova84/LittleWriter/releases

**Comment by Giova84** [comment]
Sorry for the off topic.

Hi Richard,

since I'm not very expert with GitHub, I sent you an invite to become a collaborator: you are very welcome to take part of this project as you wish.
